spring.application.name=keycloak-auth-server
server.port=8989

spring.security.oauth2.resourceserver.jwt.issuer-uri=${app.keycloak.serverUrl}/realms/${app.keycloak.realm}

app.keycloak.admin.clientId=admin-cli
app.keycloak.admin.clientSecret=MUqz9LQSNjMp3uKOEPfAyNc0o4lKFDWK
app.keycloak.realm=yastodev
app.keycloak.serverUrl=http://localhost:8080

