spring.application.name=keycloak-auth-server
server.port=9090

spring.security.oauth2.resourceserver.jwt.issuer-uri=${app.keycloak.serverUrl}/realms/${app.keycloak.realm}

app.keycloak.admin.clientId=admin-cli
app.keycloak.admin.clientSecret=yAYIBMBXSQ7QBbNU5BaEZis35EmqKamN
app.keycloak.realm=yastodev
app.keycloak.serverUrl=http://localhost:8080

