# Server port (NOT under mcp.server)
server.port=8080

# MCP Server identity
spring.ai.mcp.server.name=MCP-SERVER
spring.ai.mcp.server.version=0.1.1

spring.ai.mcp.server.protocol=STREAMABLE

spring.ai.mcp.server.type=SYNC

spring.ai.mcp.server.annotation-scanner.enabled=true