server.port=9090

spring.application.name=flowable

flowable.database-schema-update=true
flowable.async-executor-activate=false
flowable.async-history-executor-activate=false
flowable.process-definition-location-prefix=classpath*:/processes/

# Spring + Flowable DB configs
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5433/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
